image: node:lts-alpine

stages:
  - Build-Backend
  - Build-Frontend
  - Deploy-API
  - Deploy-UI

build-backend:
  stage: Build-Backend
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:latest-api" ./HideNSneak.App
    - docker push "$CI_REGISTRY_IMAGE:latest-api"
  only:
    - master

build-frontend:
  stage: Build-Frontend
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:latest-ui" ./HideNSneak.UI
    - docker push "$CI_REGISTRY_IMAGE:latest-ui"
  only:
    - master

deploy-api:
  stage: Deploy-API
  services:
  - docker:dind
  script:
    - docker login --username="$HEROKU_ACC" --password="$HEROKU_API_KEY" registry.heroku.com
    - docker tag $CI_REGISTRY_IMAGE:latest-api registry.heroku.com/$HEROKU_ACC/$HEROKU_HIDENSNEAK_APP:latest
    - docker push registry.heroku.com/$HEROKU_ACC/$HEROKU_HIDENSNEAK_APP:latest
  only:
    - master

deploy-ui:
  stage: Deploy-UI
  services:
  - docker:dind
  script:
    - docker login --username="$HEROKU_ACC" --password="$HEROKU_API_KEY" registry.heroku.com
    - docker tag $CI_REGISTRY_IMAGE:latest-ui registry.heroku.com/$HEROKU_ACC/$HEROKU_HIDENSNEAK_UI:latest
    - docker push registry.heroku.com/$HEROKU_ACC/$HEROKU_HIDENSNEAK_UI:latest
  only:
    - master
