image: docker:latest

stages:
  - Build
  - Deploy

build-backend:
  stage: Build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:latest-api" ./HideNSneak.App
    - docker push "$CI_REGISTRY_IMAGE:latest-api"
  only:
    - master

build-frontend:
  stage: Build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:latest-ui" ./HideNSneak.UI
    - docker push "$CI_REGISTRY_IMAGE:latest-ui"
  only:
    - master

deploy-api:
  stage: Deploy
  services:
  - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker tag "$CI_REGISTRY_IMAGE:latest-api" "registry.heroku.com/$HEROKU_HIDENSNEAK_APP/web:latest"
    - docker login -u "$HEROKU_ACC" -p "$HEROKU_API_KEY" registry.heroku.com
    - docker push "registry.heroku.com/$HEROKU_HIDENSNEAK_APP/web:latest"
  only:
    - master

deploy-ui:
  stage: Deploy
  services:
  - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker tag "$CI_REGISTRY_IMAGE:latest-ui" "registry.heroku.com/$HEROKU_HIDENSNEAK_UI/web:latest"
    - docker login -u "$HEROKU_ACC" -p "$HEROKU_API_KEY" registry.heroku.com
    - docker push "registry.heroku.com/$HEROKU_HIDENSNEAK_UI/web:latest"
  only:
    - master
