image: node:14.16.0

stages:
#   - Test
  - Build
  - Deploy

# test:
#   stage: test
#   script:
#     - npm install
#     - npm test

build:
  stage: Build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR/HideNSneak.App --dockerfile $CI_PROJECT_DIR/HideNSneak.App/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - master

deploy:
  stage: Deploy
  image: ruby:latest
  script:
    - apt-get update -qy && apt-get install -y ruby-dev && gem install dpl && dpl --provider=heroku --app=$HEROKU_HIDENSNEAK_APP --api-key=$HEROKU_API_KEY
  only:
    - master
