image: node:lts-alpine

stages:
  - Build
  - Deploy

build-backend:
  stage: Build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:latest-api" ./HideNSneak.App
    - docker push "$CI_REGISTRY_IMAGE:latest-api"
  only:
    - master

build-frontend:
  stage: Build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:latest-ui" ./HideNSneak.UI
    - docker push "$CI_REGISTRY_IMAGE:latest-ui"
  only:
    - master

deploy-api:
  stage: Deploy
  image: docker:latest
  services:
  - docker:dind
  before_script:
    - docker login --username "$HEROKU_ACC" --password "$HEROKU_API_KEY" registry.heroku.com
  script:
    - docker tag $CI_REGISTRY_IMAGE:latest-api registry.heroku.com/$HEROKU_HIDENSNEAK_APP/web:latest
    - docker push registry.heroku.com/$HEROKU_HIDENSNEAK_APP/web:latest
  only:
    - master

deploy-ui:
  stage: Deploy
  image: docker:latest
  services:
  - docker:dind
  before_script:
    - docker login --username "$HEROKU_ACC" --password "$HEROKU_API_KEY" registry.heroku.com
  script:
    - docker tag $CI_REGISTRY_IMAGE:latest-ui registry.heroku.com/$HEROKU_HIDENSNEAK_UI/web:latest
    - docker push registry.heroku.com/$HEROKU_HIDENSNEAK_UI/web:latest
  only:
    - master
