image: node:lts-alpine

stages:
  - Build-Backend
  - Build-Frontend
  - Deploy-API
  - Deploy-UI

build-backend:
  stage: Build-Backend
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --context-sub-path ./HideNSneak.App --dockerfile Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG-APP
  only:
    - master

build-frontend:
  stage: Build-Frontend
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --context-sub-path ./HideNSneak.UI --dockerfile Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG-UI
  only:
    - master

deploy-api:
  stage: Deploy-API
  image: ruby:alpine
  script:
    - apk add ruby-dev && gem install dpl && dpl --provider=heroku --app=$HEROKU_HIDENSNEAK_APP --api-key=$HEROKU_API_KEY
  only:
    - master

deploy-ui:
  stage: Deploy-UI
  image: ruby:alpine
  script:
    - apk add ruby-dev && gem install dpl && dpl --provider=heroku --app=$HEROKU_HIDENSNEAK_UI --api-key=$HEROKU_API_KEY
  only:
    - master
